### ISSUE TITLE
Regression with multiple domain string

### ISSUE THREAD

**Issue by seren** [gate-sso/gate#18]
The change in 9c6e9bec9c81faa6b9f6409c9edd684db258e58e causes an error when `ENV['GATE_HOSTED_DOMAINS']` is nil. Example:

```
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/app/config/initializers/devise.rb:16:in `block in (root)'
/usr/local/bundle/gems/devise-4.1.0/lib/devise.rb:280:in `setup'
/app/config/initializers/devise.rb:3:in `<main>'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:1:in `block in (root)'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:652:in `load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:651:in `block in load_config_initializer'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block in Engine'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:615:in `Engine'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:352:in `<main>'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/app/config/environment.rb:5:in `(root)'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:1:in `block in (root)'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:328:in `block in require_environment!'
/usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:457:in `run_tasks_blocks'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)
make: *** [db_setup] Error 1
```

**Comment by seren** [comment]
Nevermind. I was using a `.env` file that still had the old `GATE_HOSTED_DOMAIN` (singular) env var.
