### ISSUE TITLE
bundle exec rake db:create db:migrate db:seed fails duo to SAML missing env vars

### ISSUE THREAD

**Issue by waldman** [gate-sso/gate#71]
Hi

when trying to setup gate-oss using the README documentation It fails on the following step:
`bundle exec rake db:create db:migrate db:seed` with the following error message:

```
NoMethodError: undefined method `gsub' for nil:NilClass
/srv/app/gate/config/initializers/saml_idp.rb:6:in `block in <top (required)>'
/srv/app/gate/vendor/bundle/ruby/2.3.0/bundler/gems/saml_idp-cd646cbb9baf/lib/saml_idp.rb:18:in `configure'
/srv/app/gate/config/initializers/saml_idp.rb:1:in `<top (required)>'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/srv/app/gate/config/environment.rb:5:in `<top (required)>'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/srv/app/gate/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
```

I think that the environment variable `GATE_SAML_IDP_X509_CERTIFICATE` and `GATE_SAML_IDP_SECRET_KEY` should be set but can't find **any** information about it.

**Comment by ajeygore** [comment]
Aware of the issues, I will be able to update the documentation by tomorrow.

**Comment by ujwalendu** [comment]
hi @waldman We have updated the documentation for gate setup. Actually, the issue was introduced after SAML integration into gate . Now we have moved all SAML env vars as optional variables. These variables are required only if you are using SAML. To enable SAML please make sure to set an env var **ENABLE_SAML** to **true** along with other SAML env vars. The same has been documented in README. 

Hope it helps.

**Comment by ajeygore** [comment]
Thank you :-)
